import { type Metadata } from "next";
import { Instrument_Sans } from "next/font/google"

import type { TLayout } from "@/lib/types";
import { Toaster } from "@/components/ui/toaster"
import Navbar from "@/components/shared/navbar";

import "@/styles/globals.css";


const instrument_sans_font = Instrument_Sans({
  weight: [ "400", "500", "600", "700"],
  subsets: ["latin-ext"],
  fallback: ["serif"]
})


export const metadata: Metadata = {
  title: "lnkto",
  description: "Generated by create-t3-app",
};


export default function RootLayout({ children }: TLayout) {
  return (
    <html
      lang="en"
      className={instrument_sans_font.className}
    >
      <body>
        <Navbar />
        <main className="px-3 sm:px-8 lg:px-12 py-16">
          {children}
        </main>
        <Toaster />
      </body>
    </html>
  );
}
