import { type Metadata } from "next";
import { Montserrat } from "next/font/google"

import type { TLayout } from "@/lib/types";
import { ToastProvider } from "@/components/ui/toast";
import Navbar from "@/components/shared/navbar";

import "@/styles/globals.css";


const montserrratFont = Montserrat({
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin-ext"],
})


export const metadata: Metadata = {
  title: "lnkto",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};


export default function RootLayout({ children }: TLayout) {
  return (
    <html
      lang="en"
      className={montserrratFont.className}
    >
      <ToastProvider
        swipeDirection="down"
        duration={2}
        swipeThreshold={100}
      >
        <body>
          <Navbar />
          <main className="px-12 py-16">
            {children}
          </main>
        </body>
      </ToastProvider>
    </html>
  );
}
